In [1]:

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from PIL import Image
import copy
from sklearn.model_selection import train_test_split
import random

img,lab=[],[]
def dataset(a): # 
  global img, lab
  for bb in a: # a =[2,4,6,8,10,12,14,16,18,20]
    c = int((20-bb)/2)  # 矩陣旁邊加c個0
    H=np.zeros([bb,bb]).astype('int64')
    for j in range(bb-1):
        p1 = j+1
        p2 = j
        print(p1, p2)
        H[p1, p2] = 1
        H[p2, p1] = 1
    print(H)
    eigvals, eigvecs = la.eig(H)
    eigvals = eigvals.real
    #eigvals = eigvals.astype('float32')
    print(eigvals)
    print(eigvecs)
    eigvals_list=eigvals.tolist()
    HOMO = eigvals_list.index(sorted(eigvals_list,reverse = True)[int((bb/2)-1)])
    print(HOMO)
    LUMO = eigvals_list.index(sorted(eigvals_list,reverse = True)[int((bb/2))])
    print(LUMO)
    each_of_eig = 300
    while each_of_eig>0:  # 只要500個矩陣
      g1 = 0
      for e in range(bb):
        if each_of_eig==0:  # 只要500個矩陣
          break
        if HOMO == g1:  # label所需
          l = 0
        elif LUMO == g1:
          l = 1
        else:
          l = 2
        g1 += 1
        b1 = eigvecs[:, e].reshape(bb, 1)
        for i in range(2):  # 為了在特徵向量左右兩邊都加亂數
          b2 = copy.deepcopy([])
          while len(b2)<bb:  # 製作旁邊的矩陣
            v = random.uniform(-1,1)  # 方法返回一個隨機數，其在0至1的範圍之內
            b2.append(v)
          b2 = copy.deepcopy(np.array(b2).reshape(bb, 1))
          if i==0:
            bbb = np.concatenate((b2, b1), axis=1)
          else:  # 製作完的矩陣放在另一邊
            bbb = np.concatenate((bbb, b2), axis=1)
        #print(bbb.shape)
        bbb = copy.deepcopy(bbb[:,:, np.newaxis])
        bbb = copy.deepcopy(bbb[np.newaxis, :])
        #print(bbb.shape)
        each_of_eig-=1  # 只要500個矩陣
        if len(img) == 0:
            img = copy.deepcopy(bbb)
            lab = np.array([l])
        else:
            img = np.concatenate((img, bbb), axis=0)
            lab = np.concatenate((lab, np.array([l])), axis=0)
dataset([20])

print(img.shape, lab.shape)

X_train, X_test, y_train, y_test = train_test_split(img, lab, test_size=0.2, random_state=93483, shuffle=True)

np.save('X_train', X_train)
np.save('X_test', X_test)
np.save('y_train', y_train)
np.save('y_test', y_test)




1 0
2 1
3 2
4 3
5 4
6 5
7 6
8 7
9 8
10 9
11 10
12 11
13 12
14 13
15 14
16 15
17 16
18 17
19 18
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[-1.97766165 -1.91114561 -1.80193774 -1.6524

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from PIL import Image
import copy
from sklearn.model_selection import train_test_split
import random

img, lab,test2_lab, test2_img= [], [],[],[]
def dataset(a): # 
  global img, lab,test2_lab, test2_img
  
  for bb in a: # a =[2,4,6,8,10,12,14,16,18,20]
    img,lab=[],[]
    c = int((20-bb)/2)  # 矩陣旁邊加c個0
    H=np.zeros([bb,bb]).astype('int64')
    for j in range(bb-1):
        p1 = j+1
        p2 = j
        print(p1, p2)
        H[p1, p2] = 1
        H[p2, p1] = 1
    print(H)
    eigvals, eigvecs = la.eig(H)
    eigvals = eigvals.real
    #eigvals = eigvals.astype('float32')
    print(eigvals)
    print(eigvecs)
    eigvals_list=eigvals.tolist()
    HOMO = eigvals_list.index(sorted(eigvals_list,reverse = True)[int((bb/2)-1)])
    print(HOMO)
    LUMO = eigvals_list.index(sorted(eigvals_list,reverse = True)[int((bb/2))])
    print(LUMO)
    g1 = 0
    for e in range(bb):
      #if each_of_eig==0:  # 只要500個矩陣
      #  break
      if HOMO == g1:  # label所需
        l = 0
      elif LUMO == g1:
        l = 1
      else:
        l = 2
      g1 += 1
      b1 = eigvecs[:, e].reshape(bb, 1)
      bbb = copy.deepcopy(b1)
      #print(bbb.shape)
      bbb = copy.deepcopy(bbb[:,:, np.newaxis])
      bbb = copy.deepcopy(bbb[np.newaxis, :])
      #print(bbb.shape)
      if len(img) == 0:
        img = copy.deepcopy(bbb)
        lab = np.array([l])
        print("aaa")
      else:
        img = np.concatenate((img, bbb), axis=0)
        lab = np.concatenate((lab, np.array([l])), axis=0)
    for i in range(len(img)):
        true_img = copy.deepcopy(img[i])
        #true_img=true_img.reshape(20,1,1)
        print(true_img.shape)
        l=copy.deepcopy(lab[i])
        for j in range(len(img)):
          left_img = copy.deepcopy(img[j])
          for k in range(len(img)):
            right_img = copy.deepcopy(img[k])
            #right_img=right_img.reshape(20,1,1)
            #print(right_img.shape)
            #print(true_img.shape)
            concat_img = copy.deepcopy(np.concatenate((true_img, right_img), axis=1))
            #print(true_img.shape)
            concat_img = np.concatenate((left_img, concat_img), axis=1)
            concat_img = copy.deepcopy(concat_img[np.newaxis, :])
            #print(bbb.shape)
            if len(test2_img) == 0:
                test2_img = copy.deepcopy(concat_img)
                test2_lab = np.array([l])
                print("aaa")
            else:
                test2_img = np.concatenate((test2_img, concat_img), axis=0)
                test2_lab = np.concatenate((test2_lab, np.array([l])), axis=0)

dataset([20])

#print(train_img[0:5,:,:,:])

np.random.seed(846)
np.random.shuffle(test2_img)
np.random.seed(846)
np.random.shuffle(test2_lab)
print(test2_img,test2_lab)


np.save('X_test2', test2_img)

np.save('y_test2', test2_lab)



1 0
2 1
3 2
4 3
5 4
6 5
7 6
8 7
9 8
10 9
11 10
12 11
13 12
14 13
15 14
16 15
17 16
18 17
19 18
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[-1.97766165 -1.91114561 -1.80193774 -1.6524