<a href="https://colab.research.google.com/github/Yin-Tzu/predict_DA_reaction_product2/blob/main/4prediction_of_product_of_DA_reaction/3rdNN_dataset2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from PIL import Image
import copy
from sklearn.model_selection import train_test_split
import random
 
print(np.append([[[1],[3]],[[5],[7]]], [[[9],[11]],[[13],[15]]], axis=2))  # https://blog.csdn.net/hustqb/article/details/78090365
 
a=np.zeros(3)
a[0]=0; a[1]=1; a[2]=2
print((a==[0,1,2]).any())   #True
print((a==[0,1,2]).all())   #True
print ((a==[1,2,3]).any())        #False
print ((a==[1,2,3]).all())        #False
print ((a==[0,2,3]).any())        #True
print ((a==[0,2,3]).all())
 
def x(num):  # https://www.runoob.com/python3/python3-factorial.html
  factorial = 1
  for i in range(1,num + 1):
    factorial = factorial*i
  return factorial
rgbHOMO, rgbLUMO=[],[]
c_num_H, c_num_L = [],[]
for b in [2,4,6,8,10,12,14,16,18,20]: # f
    c = int((20-b)/2)  # 矩陣旁邊加c個0
    H=np.zeros([b,b]).astype('int64')
    for j in range(b-1):
        p1 = j+1
        p2 = j 
        #print(p1, p2)
        H[p1, p2] = 1
        H[p2, p1] = 1
    #print(H)
    eigvals, eigvecs = la.eig(H)
    eigvals = eigvals.real
    #eigvals = eigvals.astype('float32')
    #print(eigvals)
    #print(eigvecs)
    #fig = plt.imshow(eigvecs, cmap='binary')
    #plt.xticks(())
    #plt.yticks(())
    #plt.show()
    eigvals=eigvals.tolist()
    HOMO = eigvals.index(sorted(eigvals,reverse = True)[int((b/2)-1)])
    #print(HOMO)
    LUMO = eigvals.index(sorted(eigvals,reverse = True)[int((b/2))])
    #print(LUMO)
    g1 = 0
    for e in range(len(eigvals)):
      r, r1, r2 = [], 0, 0 
      pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
      ppnn = 0
      #print(pn,ppnn)
      if (HOMO == g1)and (len(eigvals)!=2):  # HOMO是雙烯，要四個碳
        while ppnn != pn:
          while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
            r1 = random.randint(0,len(eigvals)-1)
            r2 = random.randint(0,len(eigvals)-1)
          r.append([r1,r2])
          g=np.zeros(len(eigvals)).reshape(len(eigvals),1)
          bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
          re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
          #print(re)
          g[r1] = copy.deepcopy(re[r1])
          g[r2] = copy.deepcopy(re[r2])
          re[r1] = copy.deepcopy(0)
          re[r2] = copy.deepcopy(0)
          g=copy.deepcopy(g[:,:,np.newaxis])
          bl=copy.deepcopy(bl[:,:,np.newaxis])
          re=copy.deepcopy(re[:,:,np.newaxis])
          gg = []
          for i in [re,g,bl]:
            #print(c,'c')
            for d in range(c):
              i = np.insert(i, 0, np.zeros(1), 0)
              i = np.insert(i, np.size(i,0), np.zeros(1), 0)
            gg.append(i)
          re = copy.deepcopy(gg[0])
          g = copy.deepcopy(gg[1])
          bl = copy.deepcopy(gg[2])
          #print(r1,r2)
          #print(re)
          #print(g)
          reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
          regbl = np.append(reg, bl, axis=2)
          regbl = copy.deepcopy(regbl[np.newaxis, :])
          if rgbHOMO==[]:
            rgbHOMO = copy.deepcopy(regbl)
          else:
            rgbHOMO = copy.deepcopy(np.concatenate((rgbHOMO, regbl), axis=0))
          c_num_H.append(b)
          print(rgbHOMO.shape)
          print(len(c_num_H))
          ppnn += 1
      elif LUMO == g1:
        for reverse in range(2):
          u = 0
          if reverse==1:
            
            for i in range(len(eigvecs[:, e])):
              if np.sign(eigvecs[:, e][i]) != np.sign(eigvecs[:, e][::-1][i]):
                u+=1
            if u==0:
              print(eigvecs[:, e])
              break
          print(u,reverse)
          r, r1, r2 = [], 0, 0 
          pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
          ppnn = 0
          while ppnn != pn:
            while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
              r1 = random.randint(0,len(eigvals)-1)
              r2 = random.randint(0,len(eigvals)-1)
            r.append([r1,r2])
            g=np.zeros(len(eigvals)).reshape(len(eigvals),1)  # https://blog.csdn.net/qq_28618765/article/details/78085457
            bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
            if reverse==0:
              re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
              #print(re)
            else:
              re=copy.deepcopy(eigvecs[:, e][::-1].reshape(len(eigvals),1))
              #print(re)
            g[r1] = copy.deepcopy(re[r1])
            g[r2] = copy.deepcopy(re[r2])
            re[r1] = copy.deepcopy(0)
            re[r2] = copy.deepcopy(0)
            g=copy.deepcopy(g[:,:,np.newaxis])
            bl=copy.deepcopy(bl[:,:,np.newaxis])
            re=copy.deepcopy(re[:,:,np.newaxis])
            gg = []
            for i in [re,g,bl]:
              #print(c,'c')
              for d in range(c):
                i = np.insert(i, 0, np.zeros(1), 0)  # https://blog.csdn.net/weixin_37895339/article/details/78442555
                i = np.insert(i, np.size(i,0), np.zeros(1), 0)  # https://blog.csdn.net/qq_25436597/article/details/79079435
              gg.append(i)
            re = copy.deepcopy(gg[0])
            g = copy.deepcopy(gg[1])
            bl = copy.deepcopy(gg[2])
            #print(r1,r2)
            #print(re)
            #print(g)
            reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
            regbl = np.append(reg, bl, axis=2)
            regbl = copy.deepcopy(regbl[np.newaxis, :])
            if rgbLUMO==[]:
              rgbLUMO = copy.deepcopy(regbl)
            else:
              rgbLUMO = copy.deepcopy(np.concatenate((rgbLUMO, regbl), axis=0))
            #print(regbl)
            ppnn += 1
            c_num_L.append(b)
        #print(rgbLUMO.shape)
        
      else:
        l = 0
      g1 += 1
for i in range(len(rgbHOMO)):  # 判斷label
  for j in range(len(rgbLUMO)):
    #print(i,j)
    reaction_rgb = copy.deepcopy(np.append(rgbHOMO[i], rgbLUMO[j], axis=1))  # HOMOLUMO合併
    #print(reaction_rgb.shape)
    n,m=0,0
    for k in range(20):
      #print(rgbHOMO[i][k,0,1])
      if (rgbHOMO[i][k,0,1] !=0) and m==0 :
        n+=1
        #print(n)
        m=1
        HOMOT = copy.deepcopy(rgbHOMO[i][k,0,1])
        if c_num_H[i]%4 == 0:
          if k%2 != 0:
            l=0
            #print(k%2)
            break  # HOMO最上面6的反應發生位置一定要是偶數
        else:
          if k%2 != 1:
            l=0
            #print(k%2)
            break  # HOMO最上面的反應發生位置一定要是偶數
      elif (rgbHOMO[i][k,0,1] ==0) and n!=0:
        n+=1
        #print(n)
      elif (rgbHOMO[i][k,0,1] !=0) and m==1:
        if n != 3:
          l=0
          #print(rgbHOMO[i][k,0,1])
          break  # HOMO沒有隔兩格就不行
        else:
          HOMOD = copy.deepcopy(rgbHOMO[i][k,0,1])
          n1, m1 = 0,0
          for k2 in range(20):
            #print(rgbLUMO[j][k2,0,1])
            if (rgbLUMO[j][k2,0,1] !=0) and m1==0 :
              n1+=1
              #print(n)
              m1=1
              LUMOT = copy.deepcopy(rgbLUMO[j][k2,0,1])
              if c_num_L[j]%4 == 0:
                if k2%2 != 0:
                  l=0
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
              else:
                if k2%2 != 1:
                  l=0
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
            elif (rgbLUMO[j][k2,0,1] ==0) and n1!=0:
              n1+=1
              #print(n)
            elif (rgbLUMO[j][k2,0,1] !=0) and m1==1:
              #print(rgbHOMO[i][k,0,1])
              
              if n1 != 1:
                l=0
                break  # LUMO不能有格
              else:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                #print(HOMOT)
                #print(HOMOD)
                #print(LUMOT)
                #print(LUMOD)
                if (np.sign(HOMOT)==np.sign(LUMOT)) and (np.sign(HOMOD)==np.sign(LUMOD)):  # https://www.twblogs.net/a/5c4acea1bd9eee6e7d81c542
                  l=1
                  break  # 正負相同才能反映
                else:
                  l=0
                  break
            else:
              l=0
      else:
        l=0
    #print(i,j,l)
    reaction_rgb = copy.deepcopy(reaction_rgb[np.newaxis, :])
    if i==0 and j==0:
      reaction_rgb2 = copy.deepcopy(reaction_rgb)
      label = copy.deepcopy(np.array([l]))
    else:
      reaction_rgb2 = copy.deepcopy(np.concatenate([reaction_rgb2, reaction_rgb]))
      label = copy.deepcopy(np.concatenate((label, np.array([l])), axis=0))
  print(reaction_rgb2.shape, label.shape)
print(label)
"""  # 找到label為1的數據
ab = label.tolist()
print(ab)
find=1
for i,v in enumerate(ab):
  if v == find:
    print(i)
    print(reaction_rgb2[i:(i+1)], label[i:(i+1)])
"""
X_train, X_test, y_train, y_test = train_test_split(reaction_rgb2, label, test_size=0.2, random_state=20, shuffle=True)  # 打亂樣本資料順序
np.save('X_train', X_train)
np.save('X_test', X_test)
np.save('y_train', y_train)
np.save('y_test', y_test)

加入四環與八環當作會反應的產物

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from PIL import Image
import copy
from sklearn.model_selection import train_test_split
import random
 
print(np.append([[[1],[3]],[[5],[7]]], [[[9],[11]],[[13],[15]]], axis=2))  # https://blog.csdn.net/hustqb/article/details/78090365

a=np.zeros(3)
a[0]=0; a[1]=1; a[2]=2
print((a==[0,1,2]).any())	#True
print((a==[0,1,2]).all())	#True
print ((a==[1,2,3]).any())        #False
print ((a==[1,2,3]).all())        #False
print ((a==[0,2,3]).any())        #True
print ((a==[0,2,3]).all())

data122=[]
data142=[]
data144=[]
data0=[]
n22,n42,n44,n00=0,0,0,0

def x(num):  # https://www.runoob.com/python3/python3-factorial.html
  factorial = 1
  for i in range(1,num + 1):
    factorial = factorial*i
  return factorial
rgbHOMO, rgbLUMO=[],[]
c_num_H, c_num_L = [],[]
for b in [5,6]: # f
    c = int((20-b)/2)  # 矩陣旁邊加c個0
    H=np.zeros([b,b]).astype('int64')
    for j in range(b-1):
        p1 = j+1
        p2 = j 
        #print(p1, p2)
        H[p1, p2] = 1
        H[p2, p1] = 1
    #print(H)
    eigvals, eigvecs = la.eig(H)
    eigvals = eigvals.real
    #eigvals = eigvals.astype('float32')
    #print(eigvals)
    #print(eigvecs)
    #fig = plt.imshow(eigvecs, cmap='binary')
    #plt.xticks(())
    #plt.yticks(())
    #plt.show()
    eigvals=eigvals.tolist()
    HOMO = eigvals.index(sorted(eigvals,reverse = True)[int((b/2)-1)])
    #print(HOMO)
    LUMO = eigvals.index(sorted(eigvals,reverse = True)[int((b/2))])
    #print(LUMO)
    g1 = 0
    for e in range(len(eigvals)):
      r, r1, r2 = [], 0, 0 
      pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
      ppnn = 0
      #print(pn,ppnn)
      if (HOMO == g1):  # 
        while ppnn != pn:
          while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
            r1 = random.randint(0,len(eigvals)-1)
            r2 = random.randint(0,len(eigvals)-1)
          r.append([r1,r2])
          g=np.zeros(len(eigvals)).reshape(len(eigvals),1)
          bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
          re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
          #print(re)
          g[r1] = copy.deepcopy(re[r1])
          g[r2] = copy.deepcopy(re[r2])
          re[r1] = copy.deepcopy(0)
          re[r2] = copy.deepcopy(0)
          g=copy.deepcopy(g[:,:,np.newaxis])
          bl=copy.deepcopy(bl[:,:,np.newaxis])
          re=copy.deepcopy(re[:,:,np.newaxis])
          gg = []
          for i in [re,g,bl]:
            #print(c,'c')
            for d in range(c):
              i = np.insert(i, 0, np.zeros(1), 0)
              i = np.insert(i, np.size(i,0), np.zeros(1), 0)
            gg.append(i)
          re = copy.deepcopy(gg[0])
          g = copy.deepcopy(gg[1])
          bl = copy.deepcopy(gg[2])
          #print(r1,r2)
          #print(re)
          #print(g)
          reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
          regbl = np.append(reg, bl, axis=2)
          regbl = copy.deepcopy(regbl[np.newaxis, :])
          if rgbHOMO==[]:
            rgbHOMO = copy.deepcopy(regbl)
          else:
            rgbHOMO = copy.deepcopy(np.concatenate((rgbHOMO, regbl), axis=0))
          c_num_H.append(b)
          print(rgbHOMO.shape)
          print(len(c_num_H))
          ppnn += 1
      elif LUMO == g1:
        for reverse in range(2):
          u = 0
          if reverse==1:
            
            for i in range(len(eigvecs[:, e])):
              if np.sign(eigvecs[:, e][i]) != np.sign(eigvecs[:, e][::-1][i]):
                u+=1
            if u==0:
              print(eigvecs[:, e])
              break
          print(u,reverse)
          r, r1, r2 = [], 0, 0 
          pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
          ppnn = 0
          while ppnn != pn:
            while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
              r1 = random.randint(0,len(eigvals)-1)
              r2 = random.randint(0,len(eigvals)-1)
            r.append([r1,r2])
            g=np.zeros(len(eigvals)).reshape(len(eigvals),1)  # https://blog.csdn.net/qq_28618765/article/details/78085457
            bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
            if reverse==0:
              re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
              #print(re)
            else:
              re=copy.deepcopy(eigvecs[:, e][::-1].reshape(len(eigvals),1))
              #print(re)
            g[r1] = copy.deepcopy(re[r1])
            g[r2] = copy.deepcopy(re[r2])
            re[r1] = copy.deepcopy(0)
            re[r2] = copy.deepcopy(0)
            g=copy.deepcopy(g[:,:,np.newaxis])
            bl=copy.deepcopy(bl[:,:,np.newaxis])
            re=copy.deepcopy(re[:,:,np.newaxis])
            gg = []
            for i in [re,g,bl]:
              #print(c,'c')
              for d in range(c):
                i = np.insert(i, 0, np.zeros(1), 0)  # https://blog.csdn.net/weixin_37895339/article/details/78442555
                i = np.insert(i, np.size(i,0), np.zeros(1), 0)  # https://blog.csdn.net/qq_25436597/article/details/79079435
              gg.append(i)
            re = copy.deepcopy(gg[0])
            g = copy.deepcopy(gg[1])
            bl = copy.deepcopy(gg[2])
            #print(r1,r2)
            #print(re)
            #print(g)
            reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
            regbl = np.append(reg, bl, axis=2)
            regbl = copy.deepcopy(regbl[np.newaxis, :])
            if rgbLUMO==[]:
              rgbLUMO = copy.deepcopy(regbl)
            else:
              rgbLUMO = copy.deepcopy(np.concatenate((rgbLUMO, regbl), axis=0))
            #print(regbl)
            ppnn += 1
            c_num_L.append(b)
        #print(rgbLUMO.shape)
        
      else:
        l = 0
      g1 += 1
for i in range(len(rgbHOMO)):  # 判斷label
  for j in range(len(rgbLUMO)):
    #print(i,j)
    reaction_rgb = copy.deepcopy(np.append(rgbHOMO[i], rgbLUMO[j], axis=1))  # HOMOLUMO合併
    #print(reaction_rgb.shape)
    n,m=0,0
    for k in range(20):
      #print(rgbHOMO[i][k,0,1])
      if (rgbHOMO[i][k,0,1] !=0) and m==0 :
        n+=1
        #print(n)
        m=1
        HOMOT = copy.deepcopy(rgbHOMO[i][k,0,1])
        if c_num_H[i]%4 == 0:
          if k%2 != 0:
            l=copy.deepcopy(0)
            #print(k%2)
            break  # HOMO最上面的反應發生位置一定要是偶數
        else:
          if k%2 != 1:
            l=copy.deepcopy(0)
            #print(k%2)
            break  # HOMO最上面的反應發生位置一定要是偶數
      elif (rgbHOMO[i][k,0,1] ==0) and n!=0:
        n+=1
        #print(n)
      elif (rgbHOMO[i][k,0,1] !=0) and m==1:
        if n==1:  # 2接2
          HOMOD = copy.deepcopy(rgbHOMO[i][k,0,1])
          n1, m1 = 0,0
          for k2 in range(20):
            #print(rgbLUMO[j][k2,0,1])
            if (rgbLUMO[j][k2,0,1] !=0) and m1==0 :
              n1+=1
              #print(n)
              m1=1
              LUMOT = copy.deepcopy(rgbLUMO[j][k2,0,1])
              if c_num_L[j]%4 == 0:
                if k2%2 != 0:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
              else:
                if k2%2 != 1:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
            elif (rgbLUMO[j][k2,0,1] ==0) and n1!=0:
              n1+=1
              #print(n)
            elif (rgbLUMO[j][k2,0,1] !=0) and m1==1:
              #print(rgbHOMO[i][k,0,1])
              if n1 != 1:
                l=copy.deepcopy(0)
                break  # LUMO不能有格
              else:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                l=copy.deepcopy(1)
                n22+=1
                data122.append([reaction_rgb,l])
                if (c_num_L[j]==4 or c_num_L[j]==6) and (c_num_H[i]==4 or c_num_H[i]==6):
                  print(c_num_H[i], c_num_L[j],'22')
                break
            else:
              l=copy.deepcopy(0)
          
        elif n != 3:
          l=copy.deepcopy(0)
          #print(rgbHOMO[i][k,0,1])
          break  # HOMO沒有隔兩格就不行
        else:  # 4接4或4接2
          HOMOD = copy.deepcopy(rgbHOMO[i][k,0,1])
          n1, m1 = 0,0
          for k2 in range(20):
            #print(rgbLUMO[j][k2,0,1])
            if (rgbLUMO[j][k2,0,1] !=0) and m1==0 :
              n1+=1
              #print(n)
              m1=1
              LUMOT = copy.deepcopy(rgbLUMO[j][k2,0,1])
              if c_num_L[j]%4 == 0:
                if k2%2 != 0:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
              else:
                if k2%2 != 1:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
            elif (rgbLUMO[j][k2,0,1] ==0) and n1!=0:
              n1+=1
              #print(n)
            elif (rgbLUMO[j][k2,0,1] !=0) and m1==1:
              #print(rgbHOMO[i][k,0,1])
              if n1 == 3:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                l=copy.deepcopy(1)
                n44+=1
                data144.append([reaction_rgb,l])
                if (c_num_L[j]==4 or c_num_L[j]==6) and (c_num_H[i]==4 or c_num_H[i]==6):
                  print(c_num_H[i], c_num_L[j],'44')
                break
              elif n1 != 1:
                l=copy.deepcopy(0)
                break  # LUMO不能有格
              else:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                l=copy.deepcopy(1)
                n42+=1
                data142.append([reaction_rgb,l])
                if (c_num_L[j]==4 or c_num_L[j]==6) and (c_num_H[i]==4 or c_num_H[i]==6):
                  print(c_num_H[i], c_num_L[j],'42')
                break
            else:
              l=copy.deepcopy(0)
      else:
        l=copy.deepcopy(0)
    #print(i,j,l)
    if l==0:
      data0.append([reaction_rgb,l])

ooo=[78,89,87]
print(ooo[0:1]*2)
print(n22,n42,n44)
data100000=[]
random.shuffle(data0)
random.shuffle(data142)
random.shuffle(data122)
random.shuffle(data144)

for i in data0:
  if (len(data142)*3+len(data122)*3+len(data144)*3+len(data100000))>=300000:
    break
  else:
    data100000.append(i)
train,test,valid=[],[],[]
train=data142[0:int(len(data142)*0.6)]*3
test=data142[int(len(data142)*0.6):int(len(data142)*0.8)]*3
valid=data142[int(len(data142)*0.8):int(len(data142))]*3
for i in [data122,data144,data100000]:
  for j in range(len(i)):
    if j<int(len(i)*0.6):
      train.append(i[j])
      if len(i)!=len(data100000):
        train.append(i[j])
        train.append(i[j])
    elif j>=int(len(i)*0.6) and j<int(len(i)*0.8):
      test.append(i[j])
      if len(i)!=len(data100000):
        test.append(i[j])
        test.append(i[j])
    else:
      valid.append(i[j])
      if len(i)!=len(data100000):
        valid.append(i[j])
        valid.append(i[j])
#23
ttt=0
tt22=0
for i in [1,2,3,4,5,6,7,8,9,10]:
  for j in [1,2,3,4,5,6,7,8,9,10]:
    if j%2==0:
      tt22+=(i*j)
      if (i==2 and j==3) or (i==3 and j==2):
        ttt+=(i*j)
    else:
      if (i==2 and j==3) or (i==3 and j==2):
        ttt+=(i*j*2)
      tt22+=(i*j*2)
print(tt22,'tt22')
#12
tt44=0
for i in [1,2,3,4,5,6,7,8,9]:
  for j in [1,2,3,4,5,6,7,8,9]:
    if j%2==1:
      tt44+=(i*j)
      if (i==1 and j==2) or (i==2 and j==1):
        ttt+=(i*j)
    else:
      tt44+=(i*j*2)
      if (i==1 and j==2) or (i==2 and j==1):
        ttt+=(i*j*2)
print(tt44,'tt44')
#13、22
tt42=0
for i in [1,2,3,4,5,6,7,8,9]:
  for j in [1,2,3,4,5,6,7,8,9,10]:
    if j%2==0:
      tt42+=(i*j)
      if (i==1 and j==3) or (i==2 and j==2):
        ttt+=(i*j)
    else:
      tt42+=(i*j*2)
      if (i==1 and j==3) or (i==2 and j==2):
        ttt+=(i*j*2)
print(tt42,'tt42')
print(ttt,'ttt')
train=np.array(train)
test=np.array(test)
print(train.shape)
print(test.shape)
valid=np.array(valid)
print(valid.shape)
X_train, X_test, X_valid = np.array([i[0] for i in train]),np.array([i[0] for i in test]),np.array([i[0] for i in valid])
y_train, y_test, y_valid = np.array([i[1] for i in train]),np.array([i[1] for i in test]),np.array([i[1] for i in valid])

np.save('X_train', X_train)
np.save('X_test', X_test)
np.save('y_train', y_train)
np.save('y_test', y_test)
np.save('X_valid', X_valid)
np.save('y_valid', y_valid)


In [ ]:
from google.colab import files
for i in ['X_train.npy','X_test.npy','y_train.npy','y_test.npy','X_valid.npy','y_valid.npy']:
  files.download(i)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
files.download("X_test.npy")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

異常值數據集

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from PIL import Image
import copy
from sklearn.model_selection import train_test_split
import random
 
print(np.append([[[1],[3]],[[5],[7]]], [[[9],[11]],[[13],[15]]], axis=2))  # https://blog.csdn.net/hustqb/article/details/78090365

a=np.zeros(3)
a[0]=0; a[1]=1; a[2]=2
print((a==[0,1,2]).any())	#True
print((a==[0,1,2]).all())	#True
print ((a==[1,2,3]).any())        #False
print ((a==[1,2,3]).all())        #False
print ((a==[0,2,3]).any())        #True
print ((a==[0,2,3]).all())

data122=[]
data142=[]
data144=[]
data0=[]
n22,n42,n44,n00=0,0,0,0

def x(num):  # https://www.runoob.com/python3/python3-factorial.html
  factorial = 1
  for i in range(1,num + 1):
    factorial = factorial*i
  return factorial
rgbHOMO, rgbLUMO=[],[]
c_num_H, c_num_L = [],[]
for b in [2,4,6,8,10,12,14,16,18,20]: # f
    c = int((20-b)/2)  # 矩陣旁邊加c個0
    H=np.zeros([b,b]).astype('int64')
    for j in range(b-1):
        p1 = j+1
        p2 = j 
        #print(p1, p2)
        H[p1, p2] = 1
        H[p2, p1] = 1
    #print(H)
    eigvals, eigvecs = la.eig(H)
    eigvals = eigvals.real
    #eigvals = eigvals.astype('float32')
    #print(eigvals)
    #print(eigvecs)
    #fig = plt.imshow(eigvecs, cmap='binary')
    #plt.xticks(())
    #plt.yticks(())
    #plt.show()
    eigvals=eigvals.tolist()
    HOMO = eigvals.index(sorted(eigvals,reverse = True)[int((b/2)-1)])
    #print(HOMO)
    LUMO = eigvals.index(sorted(eigvals,reverse = True)[int((b/2))])
    #print(LUMO)
    g1 = 0
    for e in range(len(eigvals)):
      r, r1, r2 = [], 0, 0 
      pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
      ppnn = 0
      #print(pn,ppnn)
      if (HOMO == g1):  # HOMO是雙烯，要四個碳
        while ppnn != pn:
          while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
            r1 = random.randint(0,len(eigvals)-1)
            r2 = random.randint(0,len(eigvals)-1)
          r.append([r1,r2])
          g=np.zeros(len(eigvals)).reshape(len(eigvals),1)
          bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
          re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
          #print(re)
          g[r1] = copy.deepcopy(re[r1])
          g[r2] = copy.deepcopy(re[r2])
          re[r1] = copy.deepcopy(0)
          re[r2] = copy.deepcopy(0)
          g=copy.deepcopy(g[:,:,np.newaxis])
          bl=copy.deepcopy(bl[:,:,np.newaxis])
          re=copy.deepcopy(re[:,:,np.newaxis])
          gg = []
          for i in [re,g,bl]:
            #print(c,'c')
            for d in range(c):
              i = np.insert(i, 0, np.zeros(1), 0)
              i = np.insert(i, np.size(i,0), np.zeros(1), 0)
            gg.append(i)
          re = copy.deepcopy(gg[0])
          g = copy.deepcopy(gg[1])
          bl = copy.deepcopy(gg[2])
          #print(r1,r2)
          #print(re)
          #print(g)
          reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
          regbl = np.append(reg, bl, axis=2)
          regbl = copy.deepcopy(regbl[np.newaxis, :])
          if rgbHOMO==[]:
            rgbHOMO = copy.deepcopy(regbl)
          else:
            rgbHOMO = copy.deepcopy(np.concatenate((rgbHOMO, regbl), axis=0))
          c_num_H.append(b)
          print(rgbHOMO.shape)
          print(len(c_num_H))
          ppnn += 1
      elif LUMO == g1:
        for reverse in range(2):
          u = 0
          if reverse==1:
            
            for i in range(len(eigvecs[:, e])):
              if np.sign(eigvecs[:, e][i]) != np.sign(eigvecs[:, e][::-1][i]):
                u+=1
            if u==0:
              print(eigvecs[:, e])
              break
          print(u,reverse)
          r, r1, r2 = [], 0, 0 
          pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
          ppnn = 0
          while ppnn != pn:
            while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
              r1 = random.randint(0,len(eigvals)-1)
              r2 = random.randint(0,len(eigvals)-1)
            r.append([r1,r2])
            g=np.zeros(len(eigvals)).reshape(len(eigvals),1)  # https://blog.csdn.net/qq_28618765/article/details/78085457
            bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
            if reverse==0:
              re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
              #print(re)
            else:
              re=copy.deepcopy(eigvecs[:, e][::-1].reshape(len(eigvals),1))
              #print(re)
            g[r1] = copy.deepcopy(re[r1])
            g[r2] = copy.deepcopy(re[r2])
            re[r1] = copy.deepcopy(0)
            re[r2] = copy.deepcopy(0)
            g=copy.deepcopy(g[:,:,np.newaxis])
            bl=copy.deepcopy(bl[:,:,np.newaxis])
            re=copy.deepcopy(re[:,:,np.newaxis])
            gg = []
            for i in [re,g,bl]:
              #print(c,'c')
              for d in range(c):
                i = np.insert(i, 0, np.zeros(1), 0)  # https://blog.csdn.net/weixin_37895339/article/details/78442555
                i = np.insert(i, np.size(i,0), np.zeros(1), 0)  # https://blog.csdn.net/qq_25436597/article/details/79079435
              gg.append(i)
            re = copy.deepcopy(gg[0])
            g = copy.deepcopy(gg[1])
            bl = copy.deepcopy(gg[2])
            #print(r1,r2)
            #print(re)
            #print(g)
            reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
            regbl = np.append(reg, bl, axis=2)
            regbl = copy.deepcopy(regbl[np.newaxis, :])
            if rgbLUMO==[]:
              rgbLUMO = copy.deepcopy(regbl)
            else:
              rgbLUMO = copy.deepcopy(np.concatenate((rgbLUMO, regbl), axis=0))
            #print(regbl)
            ppnn += 1
            c_num_L.append(b)
        #print(rgbLUMO.shape)
        
      else:
        l = 0
      g1 += 1
for i in range(len(rgbHOMO)):  # 判斷label
  for j in range(len(rgbLUMO)):
    #print(i,j)
    reaction_rgb = copy.deepcopy(np.append(rgbHOMO[i], rgbLUMO[j], axis=1))  # HOMOLUMO合併
    #print(reaction_rgb.shape)
    n,m=0,0
    for k in range(20):
      #print(rgbHOMO[i][k,0,1])
      if (rgbHOMO[i][k,0,1] !=0) and m==0 :
        n+=1
        #print(n)
        m=1
        HOMOT = copy.deepcopy(rgbHOMO[i][k,0,1])
        if c_num_H[i]%4 == 0:
          if k%2 != 0:
            l=copy.deepcopy(0)
            #print(k%2)
            break  # HOMO最上面的反應發生位置一定要是偶數
        else:
          if k%2 != 1:
            l=copy.deepcopy(0)
            #print(k%2)
            break  # HOMO最上面的反應發生位置一定要是偶數
      elif (rgbHOMO[i][k,0,1] ==0) and n!=0:
        n+=1
        #print(n)
      elif (rgbHOMO[i][k,0,1] !=0) and m==1:
        if n==1:  # 2接2
          HOMOD = copy.deepcopy(rgbHOMO[i][k,0,1])
          n1, m1 = 0,0
          for k2 in range(20):
            #print(rgbLUMO[j][k2,0,1])
            if (rgbLUMO[j][k2,0,1] !=0) and m1==0 :
              n1+=1
              #print(n)
              m1=1
              LUMOT = copy.deepcopy(rgbLUMO[j][k2,0,1])
              if c_num_L[j]%4 == 0:
                if k2%2 != 0:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
              else:
                if k2%2 != 1:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
            elif (rgbLUMO[j][k2,0,1] ==0) and n1!=0:
              n1+=1
              #print(n)
            elif (rgbLUMO[j][k2,0,1] !=0) and m1==1:
              #print(rgbHOMO[i][k,0,1])
              if n1 != 1:
                l=copy.deepcopy(0)
                break  # LUMO不能有格
              else:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                l=copy.deepcopy(1)
                n22+=1
                data122.append([reaction_rgb,l])
                if (c_num_L[j]==4 or c_num_L[j]==6) and (c_num_H[i]==4 or c_num_H[i]==6):
                  print(c_num_H[i], c_num_L[j],'22')
                break
            else:
              l=copy.deepcopy(0)
          
        elif n != 3:
          l=copy.deepcopy(0)
          #print(rgbHOMO[i][k,0,1])
          break  # HOMO沒有隔兩格就不行
        else:  # 4接4或4接2
          HOMOD = copy.deepcopy(rgbHOMO[i][k,0,1])
          n1, m1 = 0,0
          for k2 in range(20):
            #print(rgbLUMO[j][k2,0,1])
            if (rgbLUMO[j][k2,0,1] !=0) and m1==0 :
              n1+=1
              #print(n)
              m1=1
              LUMOT = copy.deepcopy(rgbLUMO[j][k2,0,1])
              if c_num_L[j]%4 == 0:
                if k2%2 != 0:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
              else:
                if k2%2 != 1:
                  l=copy.deepcopy(0)
                  #print(k%2)
                  break  # HOMO最上面的反應發生位置一定要是偶數
            elif (rgbLUMO[j][k2,0,1] ==0) and n1!=0:
              n1+=1
              #print(n)
            elif (rgbLUMO[j][k2,0,1] !=0) and m1==1:
              #print(rgbHOMO[i][k,0,1])
              if n1 == 3:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                l=copy.deepcopy(1)
                n44+=1
                data144.append([reaction_rgb,l])
                if (c_num_L[j]==4 or c_num_L[j]==6) and (c_num_H[i]==4 or c_num_H[i]==6):
                  print(c_num_H[i], c_num_L[j],'44')
                break
              elif n1 != 1:
                l=copy.deepcopy(0)
                break  # LUMO不能有格
              else:
                LUMOD = copy.deepcopy(rgbLUMO[j][k2,0,1])
                l=copy.deepcopy(1)
                n42+=1
                data142.append([reaction_rgb,l])
                if (c_num_L[j]==4 or c_num_L[j]==6) and (c_num_H[i]==4 or c_num_H[i]==6):
                  print(c_num_H[i], c_num_L[j],'42')
                break
            else:
              l=copy.deepcopy(0)
      else:
        l=copy.deepcopy(0)
    #print(i,j,l)
    if l==0:
      data0.append([reaction_rgb,l])

ooo=[78,89,87]
print(ooo[0:1]*2)
print(n22,n42,n44)
data100000=[]
datatest=[]
datavalid=[]
random.shuffle(data0)
random.shuffle(data142)
random.shuffle(data122)
random.shuffle(data144)
train,test,valid=[],[],[]
for i in data0:
  if (len(data100000))>=300000 and len(datatest)<(int(len(data142))+int(len(data122))+int(len(data144))):
    datatest.append(i)
    break
  else:
    data100000.append(i)
test=data142[0:int(len(data142)*0.5)]
valid=data142[int(len(data142)*0.5):int(len(data142))]

for i in [data122,data144,datatest]:
  for j in range(len(i)):
    if j<int(len(i)*0.5):
      test.append(i[j])
    else:
      valid.append(i[j])

#23
ttt=0
tt22=0
for i in [1,2,3,4,5,6,7,8,9,10]:
  for j in [1,2,3,4,5,6,7,8,9,10]:
    if j%2==0:
      tt22+=(i*j)
      if (i==2 and j==3) or (i==3 and j==2):
        ttt+=(i*j)
    else:
      if (i==2 and j==3) or (i==3 and j==2):
        ttt+=(i*j*2)
      tt22+=(i*j*2)
print(tt22,'tt22')
#12
tt44=0
for i in [1,2,3,4,5,6,7,8,9]:
  for j in [1,2,3,4,5,6,7,8,9]:
    if j%2==1:
      tt44+=(i*j)
      if (i==1 and j==2) or (i==2 and j==1):
        ttt+=(i*j)
    else:
      tt44+=(i*j*2)
      if (i==1 and j==2) or (i==2 and j==1):
        ttt+=(i*j*2)
print(tt44,'tt44')
#13、22
tt42=0
for i in [1,2,3,4,5,6,7,8,9]:
  for j in [1,2,3,4,5,6,7,8,9,10]:
    if j%2==0:
      tt42+=(i*j)
      if (i==1 and j==3) or (i==2 and j==2):
        ttt+=(i*j)
    else:
      tt42+=(i*j*2)
      if (i==1 and j==3) or (i==2 and j==2):
        ttt+=(i*j*2)
print(tt42,'tt42')
print(ttt,'ttt')
train=np.array(train)
test=np.array(test)
print(train.shape)
print(test.shape)
valid=np.array(valid)
print(valid.shape)
X_train, X_test, X_valid = np.array([i[0] for i in train]),np.array([i[0] for i in test]),np.array([i[0] for i in valid])
y_train, y_test, y_valid = np.array([i[1] for i in train]),np.array([i[1] for i in test]),np.array([i[1] for i in valid])

np.save('X_train', X_train)
np.save('X_test', X_test)
np.save('y_train', y_train)
np.save('y_test', y_test)
np.save('X_valid', X_valid)
np.save('y_valid', y_valid)


輸入是56環

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from PIL import Image
import copy
from sklearn.model_selection import train_test_split
import random
#import calculation_eig
 
print(np.append([[[1],[3]],[[5],[7]]], [[[9],[11]],[[13],[15]]], axis=2))  # https://blog.csdn.net/hustqb/article/details/78090365
 
a=np.zeros(3)
a[0]=0; a[1]=1; a[2]=2
print((a==[0,1,2]).any())   #True
print((a==[0,1,2]).all())   #True
print ((a==[1,2,3]).any())        #False
print ((a==[1,2,3]).all())        #False
print ((a==[0,2,3]).any())        #True
print ((a==[0,2,3]).all())
 
data122=[]
data142=[]
data144=[]
data0=[]
n22,n42,n44,n00=0,0,0,0
 
def bondorder(b,eigvals_list,eigvecs,structure):
  #eigvecs橫式位置，縱是軌域
  #print(eigvals_list)
  #print(eigvecs)
  if structure=='ring':
    bo=[0]*b  # 環的話有碳數個鍵結
  else:
    bo=[0]*(b-1)  # 值鏈的話有碳數-1個鍵結
  #print(bo)
  list2 = []  # list2是儲存特爭執沒有重複的元素
  for i in sorted(eigvals_list,reverse = True):
    if not i in list2:
      list2.append(i)
  #print(list2)
  bb=copy.deepcopy(b)
  for j in range(len(list2)):
    eq_letter = np.where(np.array(eigvals_list) == list2[j])
    #print(eq_letter,'eq_letter')  # (array([2]),)
    for k in range(2):
      for i in range(len(eq_letter[0])):
        if bb==0:
          break
        #print(bb,'bb')
        bb=bb-1
        for ku in range(len(eigvecs)):
          if ku==(len(eigvecs)-1) and structure=='ring':
            bo[ku]=(eigvecs[ku][eq_letter[0][i]]*eigvecs[0][eq_letter[0][i]]+bo[ku])
            eq_letter_list = eq_letter[0].tolist()
            print(ku,eq_letter[0][i],eigvecs[ku][eq_letter[0][i]],eigvecs[0][eq_letter[0][i]])
            
          else:
            #print(eigvecs,ku,eq_letter[0][i])
            #print(eigvecs[ku][eq_letter[0][i]],'eigvecs[ku][eq_letter[0][i]]')
            if ku!=(len(eigvecs)-1):
              bo[ku]=(eigvecs[ku][eq_letter[0][i]]*eigvecs[ku+1][eq_letter[0][i]]+bo[ku])
        #print(bo)
      if bb==0:
        break
    if bb==0:
      break
  return bo
 

 
 
def x(num):  # https://www.runoob.com/python3/python3-factorial.html
  factorial = 1
  for i in range(1,num + 1):
    factorial = factorial*i
  return factorial
rgbHOMO, rgbLUMO=[],[]
c_num_H, c_num_L = [],[]
structure_H,structure_L=[],[]
double_H,double_L=[],[]

def decided(big,small,bondorder4,doubl,structure,r=None):
  global double_H,double_L
  if r==None:
    bondorder2=bondorder4
  else:
    bondorder2=bondorder4[: :-1]
    print(bondorder2)
  rrrr=0
  #print(bondorder2[small:big])
  for rrr in bondorder2[small:big]:
    if rrr>0.62:
      rrrr+=1
  #print(rrrr,(big-small))
  if big-small==3 and rrrr==2:
    doubl.append(0)
    #print('556')
  elif big-small==1 and rrrr==1:
    doubl.append(1)
    #print('654')
  elif structure=='ring':
    rrrr=0
    bondorder3=bondorder2+bondorder2
    #print(bondorder3)
    for rrr in bondorder3[big:(small+len(bondorder2))]:
      if rrr>0.62:
        rrrr+=1
    if (small+len(bondorder2))-big==3 and rrrr==2:
      doubl.append(0)
    elif (small+len(bondorder2))-big==1 and rrrr==1:
      doubl.append(1)
    else:
      doubl.append(2)
    #print('654')
  else:
    doubl.append(2)
  #print(doubl)



def chose_position_and_get_color(carbon_number_list,ring_or_straight='straight'):
  global rgbHOMO,rgbLUMO,c_num_H,c_num_L,structure_H,structure_L,double_H,double_L
  for b in carbon_number_list: # f
    #c = int((20-b)/2)  # 矩陣旁邊加c個0
    H=np.zeros([b,b]).astype('int64')
    for j in range(b-1):
        p1 = j+1
        p2 = j 
        #print(p1, p2)
        H[p1, p2] = 1
        H[p2, p1] = 1
    #print(H)
    if ring_or_straight=='ring':
      H[p1, 0] = 1
      H[0, p1] = 1
    print(H)
    #eigvals, eigvecs = calculation_eig.eig(H)
    eigvals, eigvecs = np.linalg.eig(H)
    eigvals = eigvals.real
    eigvals=np.around(eigvals,5)
    #eigvals = eigvals.astype('float32')
    #print(eigvals)
    #print(eigvecs)
    #fig = plt.imshow(eigvecs, cmap='binary')
    #plt.xticks(())
    #plt.yticks(())
    #plt.show()
    eigvals_list=eigvals.tolist()
    klk = bondorder(b,eigvals_list,eigvecs,ring_or_straight)
    print(klk)
    if b%2==1:
      homoindex=int((b//2))
    else:
      homoindex=int((b//2)-1)
    HOM=[]
    for f in range(len(eigvals_list)):
      if eigvals_list[f]==sorted(eigvals_list,reverse = True)[homoindex]:
        HOM.append(f)
    #print(HOM)
    #print(sorted(eigvals_list,reverse = True)[(sorted(eigvals_list,reverse = True).index(eigvals_list[HOM[0]])+len(HOM))])
    LUM=[]
    for f in range(len(eigvals_list)):
      if eigvals_list[f]==sorted(eigvals_list,reverse = True)[(sorted(eigvals_list,reverse = True).index(eigvals_list[HOM[0]])+len(HOM))]:
        LUM.append(f)
    #print(LUM)
    g1 = 0
    for e in range(len(eigvals)):
      r, r1, r2 = [], 0, 0 
      pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
      ppnn = 0
      #print(pn,ppnn)
      HOMl=[0 for f in range(len(HOM)) if g1==HOM[f]]
      LUMl=[0 for f in range(len(LUM)) if g1==LUM[f]]
      if (len(HOMl)>0):  # 
        while ppnn != pn:
          # 隨機選位置
          while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2:
            r1 = random.randint(0,len(eigvals)-1)
            r2 = random.randint(0,len(eigvals)-1)
          r.append([r1,r2])
          # 建立通道
          g=np.zeros(len(eigvals)).reshape(len(eigvals),1)
          bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
          re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
          #print(re)
          # 0是4個碳兩個雙鍵，1是2個碳一個雙鍵，2都不是
          if r1>r2:
            decided(r1,r2,klk,double_H,ring_or_straight)
            
          if r2>r1:
            decided(r2,r1,klk,double_H,ring_or_straight)
          # 交換數值
          g[r1] = copy.deepcopy(re[r1])
          g[r2] = copy.deepcopy(re[r2])
          re[r1] = copy.deepcopy(0)
          re[r2] = copy.deepcopy(0)
          g=copy.deepcopy(g[:,:,np.newaxis])
          bl=copy.deepcopy(bl[:,:,np.newaxis])
          re=copy.deepcopy(re[:,:,np.newaxis])
          gg = []
          if len(double_H)<10 and (double_H[-1]==0 or double_H[-1]==1):
            print(re,'88')
          # n變成20
          for i in [re,g,bl]:
            #print(c,'c')
            while len(i)<20:
              i = np.insert(i, 0, np.zeros(1), 0)
              if len(i)<20:
                i = np.insert(i, np.size(i,0), np.zeros(1), 0)
              else:
                break
            gg.append(i)
          re = copy.deepcopy(gg[0])
          g = copy.deepcopy(gg[1])
          bl = copy.deepcopy(gg[2])
          #print(r1,r2)
          #print(re)
          #print(g)
          reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
          regbl = np.append(reg, bl, axis=2)
          regbl = copy.deepcopy(regbl[np.newaxis, :])
          if rgbHOMO==[]:
            rgbHOMO = copy.deepcopy(regbl)
          else:
            rgbHOMO = copy.deepcopy(np.concatenate((rgbHOMO, regbl), axis=0))
          c_num_H.append(b)
          structure_H.append(ring_or_straight)
          #print(rgbHOMO.shape)
          #print(len(c_num_H))
          ppnn += 1
      elif len(LUMl)>0:
        for reverse in range(2):
          u = 0
          if reverse==1:
            for i in range(len(eigvecs[:, e])):
              if np.sign(eigvecs[:, e][i]) != np.sign(eigvecs[:, e][::-1][i]):
                u+=1
            if u==0:
              #print(eigvecs[:, e])
              break
          #print(u,reverse)
          r, r1, r2 = [], 0, 0 
          pn =x(len(eigvals))/((x(len(eigvals)-2))*(x(2)))
          ppnn = 0
          while ppnn != pn:
            while ([r1,r2] in r) or ([r2,r1] in r) or r1==r2: 
              r1 = random.randint(0,len(eigvals)-1)
              r2 = random.randint(0,len(eigvals)-1)
            r.append([r1,r2])
            g=np.zeros(len(eigvals)).reshape(len(eigvals),1)  # https://blog.csdn.net/qq_28618765/article/details/78085457
            bl = np.zeros(len(eigvals)).reshape(len(eigvals),1)
            if reverse==0:
              re=copy.deepcopy(eigvecs[:, e].reshape(len(eigvals),1))
              #print(re)
            else:
              re=copy.deepcopy(eigvecs[:, e][::-1].reshape(len(eigvals),1))
              #print(re)
            if r1>r2:
              decided(r1,r2,klk,double_L,ring_or_straight)
              if reverse==1:
                decided(r1,r2,klk,double_L,ring_or_straight,r=1)
            if r2>r1:
              decided(r2,r1,klk,double_L,ring_or_straight)
              if reverse==1:
                decided(r2,r1,klk,double_L,ring_or_straight,r=1)
            g[r1] = copy.deepcopy(re[r1])
            g[r2] = copy.deepcopy(re[r2])
            re[r1] = copy.deepcopy(0)
            re[r2] = copy.deepcopy(0)
            g=copy.deepcopy(g[:,:,np.newaxis])
            bl=copy.deepcopy(bl[:,:,np.newaxis])
            re=copy.deepcopy(re[:,:,np.newaxis])
            if len(double_L)<10 and (double_L[-1]==0 or double_L[-1]==1):
              print(re,'66')
            gg = []
            for i in [re,g,bl]:
              #print(c,'c')
              while len(i)<20:
                i = np.insert(i, 0, np.zeros(1), 0)  # https://blog.csdn.net/weixin_37895339/article/details/78442555
                if len(i)<20:
                  i = np.insert(i, np.size(i,0), np.zeros(1), 0)  # https://blog.csdn.net/qq_25436597/article/details/79079435
                else:
                  break
              gg.append(i)
            re = copy.deepcopy(gg[0])
            g = copy.deepcopy(gg[1])
            bl = copy.deepcopy(gg[2])
            #print(r1,r2)
            #print(re)
            #print(g)
            reg = np.append(re, g, axis=2)  #　（：：在這裡合併）
            regbl = np.append(reg, bl, axis=2)
            regbl = copy.deepcopy(regbl[np.newaxis, :])
            if rgbLUMO==[]:
              rgbLUMO = copy.deepcopy(regbl)
            else:
              rgbLUMO = copy.deepcopy(np.concatenate((rgbLUMO, regbl), axis=0))
            #print(regbl)
            ppnn += 1
            c_num_L.append(b)
            structure_L.append(ring_or_straight)
        #print(rgbLUMO.shape)
        
      else:
        l = 0
      g1 += 1
 
chose_position_and_get_color([2,4,6,8,10,12,14,16,18,20],ring_or_straight='straight')
print(len(rgbHOMO), len(c_num_H),len(structure_H),len(double_H))
print(len(rgbLUMO), len(c_num_L),len(structure_L),len(double_L))
#print(rgbHOMO[10], c_num_H[10],structure_H[10])
#print(rgbLUMO[7], c_num_L[7],structure_L[7])
chose_position_and_get_color([5,6],ring_or_straight='ring')
print(len(rgbHOMO), len(c_num_H),len(structure_H),len(double_H))
print(len(rgbLUMO), len(c_num_L),len(structure_L),len(double_L))
print(rgbHOMO[10], c_num_H[10],structure_H[10],double_H[10])
print(rgbLUMO[1030], c_num_L[1030],structure_L[1030],double_L[1030])


# 條件: 1.4個碳要兩個雙鍵 2.2個碳要一個雙鍵
# 用鍵級分辨哪裡是雙鍵
# 0是4個碳兩個雙鍵，1是2個碳一個雙鍵，2都不是

for i in range(len(rgbHOMO)):  # 判斷label
  for j in range(len(rgbLUMO)):
    #print(i,j)
    reaction_rgb = copy.deepcopy(np.append(rgbHOMO[i], rgbLUMO[j], axis=1))  # HOMOLUMO合併
    if double_H[i]==2 or double_L[j]==2:
      l=copy.deepcopy(0)
      data0.append([reaction_rgb,l])
    elif double_H[i]==0 and double_L[j]==0:
      l=copy.deepcopy(1)
      data144.append([reaction_rgb,l])
      
    elif double_H[i]==1 and double_L[j]==1:
      l=copy.deepcopy(1)
      data122.append([reaction_rgb,l])
      
    elif double_H[i]==0 and double_L[j]==1:
      l=copy.deepcopy(1)
      data142.append([reaction_rgb,l])
    else:
      l=copy.deepcopy(0)
      data0.append([reaction_rgb,l])

print(data0[6],'data0[6]')
print(data144[2],'data44[2]')
print(data122[4],'data122[4]')
print(data142[1],'data142[1]')

ooo=[78,89,87]
print(ooo[0:1]*2)
print(n22,n42,n44)
data100000=[]
random.shuffle(data0)
random.shuffle(data142)
random.shuffle(data122)
random.shuffle(data144)
print(len(data142),len(data122),len(data144),len(data0))
print(len(data142)*0.6,len(data122)*0.6,len(data144)*0.6)
print(len(data142)+len(data122)+len(data144), 'all')

HOW_much_data=1

for i in data0:
  if (len(data142)*HOW_much_data+len(data122)*HOW_much_data+len(data144)*HOW_much_data+len(data100000))>=(100000*HOW_much_data):
    break
  else:
    data100000.append(i)
train,test,valid=[],[],[]
train=data142[0:int(len(data142)*0.6)]*HOW_much_data
test=data142[int(len(data142)*0.6):int(len(data142)*0.8)]*HOW_much_data
valid=data142[int(len(data142)*0.8):int(len(data142))]*HOW_much_data
for i in [data122,data144]:
  for j in range(len(i)):
    if j<int(len(i)*0.6):
      train.append(i[j])
      if len(i)!=len(data100000):
        for ji in range((HOW_much_data-1)):
          train.append(i[j])
    elif j>=int(len(i)*0.6) and j<int(len(i)*0.8):
      test.append(i[j])
      if len(i)!=len(data100000):
        for ji in range((HOW_much_data-1)):
          test.append(i[j])
    else:
      valid.append(i[j])
      if len(i)!=len(data100000):
        for ji in range((HOW_much_data-1)):
          valid.append(i[j])

for j in range(len(data100000)):
  if len(train)<int(100000*0.6*HOW_much_data):
    train.append(data100000[j])
  elif len(test)<int(100000*0.2*HOW_much_data):
    test.append(data100000[j])
  else:
    valid.append(data100000[j])


train=np.array(train)
test=np.array(test)
print(train.shape)
print(test.shape)
valid=np.array(valid)
print(valid.shape)
X_train, X_test, X_valid = np.array([i[0] for i in train]),np.array([i[0] for i in test]),np.array([i[0] for i in valid])
y_train, y_test, y_valid = np.array([i[1] for i in train]),np.array([i[1] for i in test]),np.array([i[1] for i in valid])

np.save('X_train', X_train)
np.save('X_test', X_test)
np.save('y_train', y_train)
np.save('y_test', y_test)
np.save('X_valid', X_valid)
np.save('y_valid', y_valid)


[[[ 1  9]
  [ 3 11]]

 [[ 5 13]
  [ 7 15]]]
True
True
False
False
True
False
[[0 1]
 [1 0]]
[0.9999999999999998]
[[[0.]]

 [[0.]]] 88
[[[0.]]

 [[0.]]] 66
[0.9999999999999998]
[[[0.]]

 [[0.]]] 66
[[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 1 0]]
[0.8944271909999161, 0.44721359549995776, 0.894427190999916]
[[[ 0.        ]]

 [[-0.37174803]]

 [[-0.37174803]]

 [[ 0.        ]]] 66
[[[ 0.        ]]

 [[ 0.        ]]

 [[-0.37174803]]

 [[ 0.60150096]]] 66
[[[ 0.60150096]]

 [[-0.37174803]]

 [[ 0.        ]]

 [[ 0.        ]]] 66
[[[0.        ]]

 [[0.        ]]

 [[0.37174803]]

 [[0.60150096]]] 88
[[[-0.60150096]]

 [[-0.37174803]]

 [[ 0.        ]]

 [[ 0.        ]]] 88
[[[ 0.        ]]

 [[-0.37174803]]

 [[ 0.37174803]]

 [[ 0.        ]]] 88
[[0 1 0 0 0 0]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [0 0 0 0 1 0]]
[0.871119239863516, 0.4834347061800275, 0.784851315347847, 0.4834347061800274, 0.8711192398635157]
[0.8711192398635157, 0.4834347061800274, 0.784851315347847, 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:294: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:222: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


[0.8576277664439459, 0.4999665405877761, 0.7468524065642335, 0.5440415515550789, 0.7296976530302068, 0.5440415515550777, 0.7468524065642308, 0.4999665405877755, 0.8576277664439451]
[0.8576277664439459, 0.4999665405877761, 0.7468524065642335, 0.5440415515550789, 0.7296976530302068, 0.5440415515550777, 0.7468524065642308, 0.4999665405877755, 0.8576277664439451]
[0.8576277664439459, 0.4999665405877761, 0.7468524065642335, 0.5440415515550789, 0.7296976530302068, 0.5440415515550777, 0.7468524065642308, 0.4999665405877755, 0.8576277664439451]
[0.8576277664439459, 0.4999665405877761, 0.7468524065642335, 0.5440415515550789, 0.7296976530302068, 0.5440415515550777, 0.7468524065642308, 0.4999665405877755, 0.8576277664439451]
[0.8576277664439459, 0.4999665405877761, 0.7468524065642335, 0.5440415515550789, 0.7296976530302068, 0.5440415515550777, 0.7468524065642308, 0.4999665405877755, 0.8576277664439451]
[0.8576277664439459, 0.4999665405877761, 0.7468524065642335, 0.5440415515550789, 0.729697653030

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:401: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:402: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:405: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


(60000, 2)
(20000, 2)
(20000, 2)


In [ ]:
import numpy as np
np.__file__

'/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'